### ISSUE TITLE
OpenSRS::Response#success?

### ISSUE THREAD

**Issue by Veejay** [voxxit/opensrs#19]
Hi,

I was wondering how come the success? method on the OpenSRS::Response returns true when the is_success attribute is not set on the response?

I would expect that the absence of this attribute is more likely a sign of failure or problem than a sign of success. Any thoughts?

**Comment by voxxit** [comment]
Actually looking back at this @Veejay, I believe that is simply the way the (very old) OpenSRS XML API works. Check the documents to be sure, but I am pretty sure there were a few methods I would call where is_success would not be returned in the response, so we'd just assume it was successful.

**Comment by voxxit** [comment]
I'll close this for now, but if you find specific cases where this isn't the case, I'll be happy to fix them case-by-case.
