### ISSUE TITLE
why do we need to pass in the password when instantiating the server?

### ISSUE THREAD

**Issue by dfguo** [voxxit/opensrs#30]
why do we need to pass in the password when instantiating the server? I don't think it's being used.

**Comment by voxxit** [comment]
@dfguo Are there any specs for it? I believe there are parts of the API which require authenticated connection, and that connection is reused from there, but I can't be sure as it has been a while since I've looked at how it is instantiated. 

If not, let's remove it!

**Comment by dfguo** [comment]
It's used in the code case. I will remove it. Thanks!
